### ISSUE TITLE
如图,独立服务器无法运行

### ISSUE THREAD

**Issue by Shuazijun** [yuxuanchiadm/SkyCraftUpdater#1]
环境 Centos8  Java16
![image](https://user-images.githubusercontent.com/30001049/123507018-c1852180-d699-11eb-8129-2616258da1eb.png)

**Comment by yuxuanchiadm** [comment]
请提供具体版本和更新服务器启动脚本

**Comment by Shuazijun** [comment]
![image](https://user-images.githubusercontent.com/30001049/123507937-111a1c00-d69f-11eb-8719-a47c52b4be61.png)

**Comment by yuxuanchiadm** [comment]
使用
```
java -cp Updater-1.16.5-2.1.0.jar org.skycraft.updater.core.Provider client client_manifest.json 0.0.0.0 80
```
启动服务端，确保`Updater-1.16.5-2.1.0.jar`在当前目录下
