### ISSUE TITLE
1.16.5 FML check problem

### ISSUE THREAD

**Issue by Sam-Chai** [yuxuanchiadm/SkyCraftUpdater#13]
![image](https://user-images.githubusercontent.com/29940426/151706032-dca045da-7e1b-4782-8ef8-9b3bb52d15f7.png)
here it is.
it reports me a BIG RED CORSS
the log:
`[23:24:23] [Netty Client IO #0/INFO]: Client has mods that are missing on server: [updater]`
could updater can run in server's mod folder? if not so, please fix it. thx

**Comment by yuxuanchiadm** [comment]
You need to place jar file in server's plugins directory
